# <img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: passes the data directly to the first hidden layer where the data is multiplied by the first hidden layers weights
### Hidden Layer: is the layer between the input layer and the outer layer where the neurons take in a set weighted input.
### Output Layer: is the last layer of neurons that produces given outputs for the program 
### Neuron: is a mathematical function that model the functioning of a biological neuron. It also computes the weighted avg of its inputs  and this sum is then passed through a nonliner function such as signoid
### Weight: are use to connect neurons in one layer to neurons in the next layer 
### Activation Function:is responsible for transforming the summed weighted inputs tfrom the node into the activation of the node or out put for theat input
### Node Map: it si a visual diagarm of the architecture of our neural network. It shows that path from inputs to out puts 
### Perceptron: is a machine learning algorthim that helps to provide classified outcomes for computing 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### inputs pass data directly thru the first layer to the hidden layer where fliter thru weights and bias then thru a activation layer to the out put layer  

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [2]:
import pandas as pd
import numpy as np 
np.random.seed(812)
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,1]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
##### Your Code Here #####

df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  1

In [4]:
corr = [[1],[1],[1],[0]]

In [5]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_d(x):
    sx = sigmoid(x)
    return sx*(1-sx)

In [6]:
#since we have correct outpusts as y and input data all we really needed is to get random weights

weight = 2*np.random.random((3, 1)) -1
weight

array([[ 0.0099616 ],
       [ 0.21185521],
       [-0.08502562]])

In [7]:
#Inputs 
inputs = df.values

In [10]:
for _ in range(3):
    weight_sum = np.dot(inputs, weight)
    print(f"Weighted sum: {weight_sum}")
    
    activate = sigmoid(weight_sum)
    
    err = corr - activate
    
    adj= err*sigmoid_d(activate) #you should increase the weights by the corresponding a
    
    weight += np.dot(inputs.T, adj)


print("Weights after training")
print(weight)

print("Output after training")
print(activate)

Weighted sum: [[17.81063898]
 [ 5.9694557 ]
 [ 5.9694557 ]
 [-5.87172757]]
Weighted sum: [[17.81094002]
 [ 5.969556  ]
 [ 5.969556  ]
 [-5.87182802]]
Weighted sum: [[17.81124103]
 [ 5.96965629]
 [ 5.96965629]
 [-5.87192845]]
Weights after training
[[-11.84178544]
 [-11.84178544]
 [ 17.81154201]]
Output after training
[[0.99999998]
 [0.99745139]
 [0.99745139]
 [0.00280952]]



## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
len(diabetes.columns)

9

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [14]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1] # takes of the last column
scale = MinMaxScaler()
X = scale.fit_transform(diabetes[feats])
d_norm = pd.DataFrame(X)

/Users/alxander44/anaconda3/envs/U4-S1-NLP/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [15]:
d_norm.head()


0         1         2         3         4         5         6  \
0  0.352941  0.743719  0.590164  0.353535  0.000000  0.500745  0.234415   
1  0.058824  0.427136  0.540984  0.292929  0.000000  0.396423  0.116567   
2  0.470588  0.919598  0.524590  0.000000  0.000000  0.347243  0.253629   
3  0.058824  0.447236  0.540984  0.232323  0.111111  0.418778  0.038002   
4  0.000000  0.688442  0.327869  0.353535  0.198582  0.642325  0.943638   

          7  
0  0.483333  
1  0.166667  
2  0.183333  
3  0.000000  
4  0.200000

In [16]:
X_test= d_norm.iloc[500:]
X_train = d_norm.iloc[0:500]

In [ ]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?