<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** is a mathematical function that models the functioning of a biological neuron. A neuron computes the weighted average of its imputs and this sum is then passed throught a nonliner function (activation function) such as signoid
- **Input Layer:** passes the data directly to the first hidden layer where the data is muliplied by the wieghts of the hidden layers
- **Hidden Layer:** the hidden layer is the layer thatis between the input layer and the output layer and where the artifical neurons take inputs
- **Output Layer:** is the last layer of neurons that produce a given output for the program 
- **Activation:** the activation function is reponsible for transforming the summed weighted inputs into an output. Relu or sigmoid is commonly used. 
- **Backpropagation:** is an algorrithm that deturmis how a single training example will nudge the weights and bais. It feeds information back to the pervious nodes based on the errors of the out put in order to learn and increase predictions and decrease the cost.


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [3]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values
candy.shape
#X_train = X[0:7500]
#y_train = y[0:7500]
#x_test = X[7500:10000]
#y_test = y[7500:10000]

(10000, 3)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
class Perceptron(object):
    
    def __init__(self, no_of_x, niter=5000, learning_rate=0.01):
        self.niter = niter
        self.learning_rate = learning_rate
        self.weights = np.zeros(no_of_x + 1)
        self.errors_ = []
    
    def transform_df(self, df, target):
        X = df.drop(columns=target).to_numpy()
        y = df[target].to_numpy()
        X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
        y_train = y_train.reshape(-1, 1)
        y_test = y_test.reshape(-1, 1)
        return X_train, X_test, y_train, y_test
    
    def net_input(self, X_test):
        """Calculate net input"""
        return np.dot(X_test, self.weights[1:]) + self.weights[0]

    def predict(self, X_test):
        """Return class label after unit step"""
        return np.where(self.net_input(X_test) >= 0.0, 1, -1)
    
    def Errors(self):
        return self.errors_

    def train(self, X_train, y_train):        
        for _ in range(self.niter):
            for row, target in zip(X_train, y_train):
                prediction = self.predict(row)
                delta_w = self.learning_rate * (target - prediction)
                self.weights[1:] += delta_w * row
                self.weights[0] += delta_w
                
    def rmse(self, X_test, y_test):
        return np.sqrt(np.mean((self.predict(X_test) - y_test) ** 2))
    
    def acc(self, y_true, y_pred):
        return accuracy_score(y_true, y_pred)

    
pn = Perceptron(2)
X_train, X_test, y_train, y_test = pn.transform_df(candy, 'ate')
pn.train(X_train, y_train)
y_pred = pn.predict(X_test)
pn.acc(y_test, y_pred)

0.4915

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [11]:
# from the lecture
class NeuralNetwork:
    def __init__(self, input_size=2, hidden_size=8, output_size=1, lr=0.01):
        # Set up Architecture of Neural Network
        self.lr = lr

        # Initial Weights
        self.weights1 = np.random.rand(input_size, hidden_size) * 0.1
       
        self.weights2 = np.random.rand(hidden_size, output_size) * 0.1
    
        self.Bh = np.zeros(hidden_size)
        
        self.Bo = np.zeros(output_size)
        
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def relu(self, s):
        return np.maximum(0, s)
    
    def leaky_relu(self, s):
        return np.maximum(0.1 * s, s)
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1) + self.Bh

        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2) + self.Bo
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta) * self.lr
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) * self.lr
        # Adjustments to hidden bias
        self.Bh += np.sum(self.z2_delta) * self.lr
        #Adjustments to output bias
        self.Bo += np.sum(self.o_delta) * self.lr

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)
    
    def acc(self, y_true):
        y_pred = self.feed_forward(X)
        return accuracy_score(y_true, y_pred)
        

nn = NeuralNetwork()

for i in range(8000):
    if ((i+1) % 2000 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---' * 3 + '+')
        print('The Error', nn.o_error)
        print('The Input: \n', X_test)
        print('Actual Output: \n', y_test)
        print('Prediction Output: \n', str(nn.feed_forward(X_test)))
        print('The Loss: \n', str(np.mean(np.square(y_test - nn.feed_forward(X_test)))))
    nn.train(X_train, y_train)
    
print(y_test - nn.feed_forward(X_test))

+---------EPOCH 2000---------+
The Error [[ 0.05298387]
 [ 0.05298387]
 [ 0.05145325]
 ...
 [-0.05313403]
 [-0.05313403]
 [ 0.05298387]]
The Input: 
 [[0 1]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 1]
 [0 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [0]
 [0]]
Prediction Output: 
 [[0.94701662]
 [0.94854689]
 [0.94854689]
 ...
 [0.94854689]
 [0.06145964]
 [0.05313827]]
The Loss: 
 0.04932890967864855
+---------EPOCH 4000---------+
The Error [[ 0.05276422]
 [ 0.05276422]
 [ 0.05139326]
 ...
 [-0.05596298]
 [-0.05596298]
 [ 0.05276422]]
The Input: 
 [[0 1]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 1]
 [0 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [0]
 [0]]
Prediction Output: 
 [[0.9472358 ]
 [0.94860675]
 [0.94860675]
 ...
 [0.94860675]
 [0.05884625]
 [0.05596351]]
The Loss: 
 0.04932251959727184
+---------EPOCH 6000---------+
The Error [[ 0.05274457]
 [ 0.05274457]
 [ 0.05139098]
 ...
 [-0.05664988]
 [-0.05664988]
 [ 0.05274457]]
The Input: 
 [[0 1]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 1]
 [0 0]]
Actual Output:

In [44]:
y_pred = nn.feed_forward(X_test)
rounds = [round(x[0]) for x in y_pred]
y_pred1 = np.array(rounds, dtype='int64')
accuracy_score(y_test, y_pred1)*100

94.8

In [17]:
P.S. Don't try candy gummy bears. They're disgusting. 

SyntaxError: invalid syntax (<ipython-input-17-283961ae716b>, line 1)

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [18]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
117   56    1   3       120   193    0        0      162      0      1.9   
114   55    1   1       130   262    0        1      155      0      0.0   
63    41    1   1       135   203    0        1      132      0      0.0   
286   59    1   3       134   204    0        1      162      0      0.8   
134   41    0   1       126   306    0        1      163      0      0.0   

     slope  ca  thal  target  
117      1   0     3       1  
114      2   0     2       1  
63       1   0     1       1  
286      2   2     2       0  
134      2   0     2       1

In [24]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [25]:
X2 = df.drop(columns='target')
y2 = df.target

ss = StandardScaler()
X3 = ss.fit_transform(X2)

X3_train, X3_test, y2_train, y2_test = train_test_split(X3, y2, stratify=y2)
# looking back i probably should of chose different or better var names. 

In [35]:
def create_model():
    # create model
    model = Sequential()
    
    model.add(Dense(20, input_dim=13, activation='relu'))
    
    model.add(Dense(20, activation='relu'))
    
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    
    return model

# create model
model = KerasClassifier(build_fn=create_model, batch_size=30, epochs=30, verbose=1)
model.fit(X3_train, y2_train)

Train on 227 samples
Epoch 1/30
227/227 [==============================] - 0s 1ms/sample - loss: 0.6869 - accuracy: 0.5463
Epoch 2/30
227/227 [==============================] - 0s 55us/sample - loss: 0.6444 - accuracy: 0.5947
Epoch 3/30
227/227 [==============================] - 0s 46us/sample - loss: 0.6100 - accuracy: 0.6740
Epoch 4/30
227/227 [==============================] - 0s 47us/sample - loss: 0.5806 - accuracy: 0.7004
Epoch 5/30
227/227 [==============================] - 0s 47us/sample - loss: 0.5550 - accuracy: 0.7489
Epoch 6/30
227/227 [==============================] - 0s 49us/sample - loss: 0.5317 - accuracy: 0.7885
Epoch 7/30
227/227 [==============================] - 0s 48us/sample - loss: 0.5113 - accuracy: 0.7797
Epoch 8/30
227/227 [==============================] - 0s 46us/sample - loss: 0.4921 - accuracy: 0.7885
Epoch 9/30
227/227 [==============================] - 0s 51us/sample - loss: 0.4751 - accuracy: 0.8062
Epoch 10/30
227/227 [==============================] 

In [40]:
def create_model():
    # create model
    model = Sequential()
    
    model.add(Dense(20, input_dim=13, activation='relu'))
    
    model.add(Dense(20, activation='relu'))
    
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

p = {'batch_size': [20], 'epochs': [25, 50, 75, 100, 125] }
              
              
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=p, n_jobs=1)
grid_result = grid.fit(X3_train, y2_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"The Means: {mean}, The Stdev: {stdev} with: {param}") 

/Users/alxander44/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best: 0.8237885438923268 using {'batch_size': 20, 'epochs': 25}
The Means: 0.8237885438923268, The Stdev: 0.022751957790349005 with: {'batch_size': 20, 'epochs': 25}
The Means: 0.7665198321909631, The Stdev: 0.03440547693433672 with: {'batch_size': 20, 'epochs': 50}
The Means: 0.7709251216854818, The Stdev: 0.044768005744855954 with: {'batch_size': 20, 'epochs': 75}
The Means: 0.7709251069812523, The Stdev: 0.023477718579525426 with: {'batch_size': 20, 'epochs': 100}
The Means: 0.7709250922770227, The Stdev: 0.02697063222696695 with: {'batch_size': 20, 'epochs': 125}


In [55]:
model = KerasClassifier(build_fn = create_model, verbose=1, batch_size=20, epochs=175)# this may be over fit in terms of the number of epochs
# but i really wanted to get as close as i could to 99% so <kanye shrug>
model.fit(X3_train,y2_train)

Train on 227 samples
Epoch 1/175
227/227 [==============================] - 0s 2ms/sample - loss: 0.6376 - accuracy: 0.6740
Epoch 2/175
227/227 [==============================] - 0s 69us/sample - loss: 0.5857 - accuracy: 0.7313
Epoch 3/175
227/227 [==============================] - 0s 70us/sample - loss: 0.5455 - accuracy: 0.7577
Epoch 4/175
227/227 [==============================] - 0s 72us/sample - loss: 0.5132 - accuracy: 0.8018
Epoch 5/175
227/227 [==============================] - 0s 71us/sample - loss: 0.4846 - accuracy: 0.8018
Epoch 6/175
227/227 [==============================] - 0s 74us/sample - loss: 0.4599 - accuracy: 0.8106
Epoch 7/175
227/227 [==============================] - 0s 70us/sample - loss: 0.4382 - accuracy: 0.8326
Epoch 8/175
227/227 [==============================] - 0s 72us/sample - loss: 0.4206 - accuracy: 0.8414
Epoch 9/175
227/227 [==============================] - 0s 77us/sample - loss: 0.4049 - accuracy: 0.8502
Epoch 10/175
227/227 [======================